In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [3]:
csv_filename = 'PCA1.csv'
df = pd.read_csv(csv_filename)

print(df.head())

    X   Y
0   4  11
1   8   4
2  13   5
3   7  14


In [4]:
num_rows, num_columns = df.shape
print("Number of Features:", num_columns)
print("Number of Samples:", num_rows)

Number of Features: 2
Number of Samples: 4


In [5]:
featuredata = [4,8,13,7]
mean_x = np.mean(featuredata)
print("Mean of feature (X):", mean_x)

Mean of feature (X): 8.0


In [6]:
sampledata = [11,4,5,14]
mean_y = np.mean(sampledata)
print("Mean of sample (Y):", mean_y)

Mean of sample (Y): 8.5


In [7]:

# Compute the covariance matrix
X = np.array([4,8,13,7])
Y = np.array([11,4,5,14])

covariance_matrix = np.cov(X, Y)

print("Covariance Matrix :")
print(covariance_matrix)

Covariance Matrix :
[[ 14. -11.]
 [-11.  23.]]


In [8]:

eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

print("\nNormalized Eigenvectors:")
print(normalized_eigenvectors)

Eigenvalues:
[ 6.61513568 30.38486432]

Eigenvectors:
[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]

Normalized Eigenvectors:
[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]


In [10]:

x = np.array([4,8,13,7])
y = np.array([11, 4,5,14])
xy = np.concatenate(([x-mean_x],[y-mean_y]), axis=0)
xy

array([[-4. ,  0. ,  5. , -1. ],
       [ 2.5, -4.5, -3.5,  5.5]])